import { useCallback, useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { Layers } from "lucide-react";
import { type RecentModel, getRecentModelScreenshotUrl } from "../api/public.api";

interface RecentModelsCarouselProps {
  models: RecentModel[];
}

interface LayoutConfig {
  columns: number;
  rows: number;
}

/** Responsive layout: columns × rows visible at once. */
function getLayout(): LayoutConfig {
  if (typeof window === "undefined") return { columns: 5, rows: 1 };
  if (window.innerWidth >= 768) return { columns: 5, rows: 1 };
  if (window.innerWidth >= 640) return { columns: 3, rows: 1 };
  return { columns: 2, rows: 2 }; // 2×2 grid on mobile
}

export function RecentModelsCarousel({ models }: RecentModelsCarouselProps) {
  const [queue, setQueue] = useState(() => [...models]);
  const [sliding, setSliding] = useState(false);
  const [paused, setPaused] = useState(false);
  const [layout, setLayout] = useState(getLayout);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Keep queue in sync if models prop changes
  useEffect(() => {
    setQueue([...models]);
  }, [models]);

  // Track responsive breakpoint
  useEffect(() => {
    const onResize = () => setLayout(getLayout());
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);

  const { columns, rows } = layout;

  const rotate = useCallback(() => {
    setSliding(true);
    // After CSS transition, shift out one column (= `rows` items)
    timerRef.current = setTimeout(() => {
      setQueue((prev) => [...prev.slice(rows), ...prev.slice(0, rows)]);
      setSliding(false);
    }, 500);
  }, [rows]);

  // Auto-rotation interval
  useEffect(() => {
    if (paused || queue.length <= columns * rows) return;
    const id = setInterval(rotate, 5000);
    return () => {
      clearInterval(id);
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [paused, rotate, queue.length, columns, rows]);

  if (models.length === 0) return null;

  const gapRem = 1;
  // Column width: each visible column takes 1/columns of container minus gaps between columns
  const colCalc = `calc((100% - ${(columns - 1) * gapRem}rem) / ${columns})`;
  // Shift distance: one column width + one gap
  const shiftCalc = `calc((100% - ${(columns - 1) * gapRem}rem) / ${columns} + ${gapRem}rem)`;

  return (
    <section className="rounded-2xl bg-[linear-gradient(135deg,#0f172a_0%,#1e293b_40%,#134e4a_100%)] p-4 text-slate-100 sm:p-6 md:p-8 lg:p-12">
      {/* Section header */}
      <div className="mb-4 space-y-2 sm:mb-6">
        <p className="inline-flex items-center gap-2 rounded-full border border-white/20 px-3 py-1 text-xs uppercase tracking-[0.2em] text-emerald-200">
          <Layers className="h-3.5 w-3.5" />
          Model Library
        </p>
        <h2 className="text-xl font-semibold md:text-2xl">Top-rated from the library</h2>
        <p className="text-sm text-slate-300">
          The best models from each category — generated by our AI pipeline.
        </p>
      </div>

      {/* Carousel track */}
      <div
        className="overflow-hidden"
        onMouseEnter={() => setPaused(true)}
        onMouseLeave={() => setPaused(false)}
      >
        <div
          style={{
            display: "grid",
            gridTemplateRows: `repeat(${rows}, 1fr)`,
            gridAutoFlow: "column",
            gridAutoColumns: colCalc,
            columnGap: `${gapRem}rem`,
            rowGap: `${rows > 1 ? 0.75 : 0}rem`,
            transform: sliding ? `translateX(calc(-1 * ${shiftCalc}))` : "translateX(0)",
            transition: sliding ? "transform 500ms ease-in-out" : "none",
          }}
        >
          {queue.map((model) => (
            <Link
              key={model.id}
              to={`/gallery/category/${encodeURIComponent(model.categoryId)}?highlight=${encodeURIComponent(model.id)}`}
              className="shrink-0 rounded-xl border border-white/15 bg-black/20 p-3 transition hover:border-emerald-400/40 hover:bg-black/30"
            >
              <div className="aspect-square overflow-hidden rounded-lg bg-black/30">
                <img
                  src={getRecentModelScreenshotUrl(model.id)}
                  alt={model.promptText}
                  className="h-full w-full object-contain"
                  loading="lazy"
                  onError={(e) => {
                    (e.currentTarget.parentElement as HTMLElement).classList.add("hidden");
                  }}
                />
              </div>
              <p className="mt-2 truncate text-sm font-medium text-slate-100" title={model.promptText}>
                {model.promptText}
              </p>
              <p className="truncate text-xs text-emerald-200/70">{model.categoryName}</p>
            </Link>
          ))}
        </div>
      </div>

      {/* Explore button */}
      <div className="mt-4 flex justify-center sm:mt-6">
        <Link
          to="/gallery"
          className="inline-flex items-center gap-2 rounded-md border border-white/20 bg-white/10 px-5 py-2.5 text-sm font-medium text-slate-100 transition hover:bg-white/20"
        >
          <Layers className="h-4 w-4 text-emerald-200" />
          Explore our library...
        </Link>
      </div>
    </section>
  );
}
