/**
 * Workbench Embeddings Service
 *
 * Generates and stores vector embeddings for workbench example prompts.
 * Used for semantic similarity search when selecting few-shot examples
 * for the code generation pipeline.
 */

import { trackedEmbed, trackedEmbedMany } from "./tracked-llm.service.js";
import { asQuotaError } from "../utils/llm-errors.js";
import { prisma } from "../db/prisma.js";
import { createLogger } from "../utils/logger.js";
import {
  getModelForPurpose,
  createEmbeddingModel,
  type LlmModelConfig,
} from "./llm-config.service.js";
import { isSpecEmbeddingEnabled } from "./generation-settings.service.js";

const logger = createLogger("embeddings");

// ── Types ────────────────────────────────────────────────────────────

export interface FewShotMatch {
  prompt: string;
  code: string;
  similarity: number;
}

export interface EmbeddingStatus {
  total: number;
  embedded: number;
  missing: number;
  stale: number;
  currentModel: string;
}

export interface BackfillResult {
  embedded: number;
  skipped: number;
}

// ── Provider setup ──────────────────────────────────────────────────

// Target dimension for pgvector index compatibility (max 2000 for HNSW/IVFFlat)
// text-embedding-3-large with dimensions=1536 produces better quality than
// text-embedding-3-small at the same dimension via Matryoshka Representation Learning.
const EMBEDDING_DIMENSIONS = 1536;

/**
 * Resolve the embedding model from the DB-driven llm_purpose_map.
 * Returns the Vercel AI SDK embedding model instance and config.
 */
async function resolveEmbeddingConfig(): Promise<{ model: ReturnType<typeof createEmbeddingModel>; config: LlmModelConfig }> {
  const cfg = await getModelForPurpose("embedding");
  const model = createEmbeddingModel(cfg);
  return { model, config: cfg };
}

// ── Core embedding functions ────────────────────────────────────────

/**
 * Embed a single text string into a vector.
 */
export async function embedPromptText(text: string): Promise<number[]> {
  const { embedding } = await embedPromptTextWithUsage(text);
  return embedding;
}

/**
 * Embed a single text string into a vector, also returning token usage.
 */
export async function embedPromptTextWithUsage(text: string): Promise<{ embedding: number[]; tokens: number }> {
  const { model, config: cfg } = await resolveEmbeddingConfig();
  try {
    const result = await trackedEmbed({
      model,
      value: text,
      providerOptions: { openai: { dimensions: EMBEDDING_DIMENSIONS } },
    }, {
      purpose: "embeddings",
      providerName: cfg.provider,
      modelId: cfg.id,
      modelName: cfg.modelName,
      modelConfig: {
        costPer1mInput: cfg.costPer1mInput,
        costPer1mOutput: cfg.costPer1mOutput,
      },
    });
    return { embedding: result.embedding, tokens: result.usage?.tokens ?? 0 };
  } catch (error) {
    const quotaError = asQuotaError(error, cfg.provider);
    if (quotaError) throw quotaError;
    throw error;
  }
}

/**
 * Embed a prompt (+ optional description) and store the vector + model name.
 * When a description is available, embeds `prompt + description` together so
 * the vector captures both what the model IS and what techniques it TEACHES.
 */
export async function embedAndStorePrompt(promptId: string, promptText: string, description?: string | null): Promise<void> {
  const { config: embeddingCfg } = await resolveEmbeddingConfig();
  const textToEmbed = description
    ? `${promptText}\n\n${description}`
    : promptText;
  const embedding = await embedPromptText(textToEmbed);
  const pgVector = `[${embedding.join(",")}]`;
  await prisma.$executeRaw`
    UPDATE workbench_example_prompts SET embedding = ${pgVector}::vector, embedding_model = ${embeddingCfg.modelName} WHERE id = ${promptId}::uuid
  `;
}

// ── Backfill ────────────────────────────────────────────────────────

/**
 * Batch-embed prompts that have approved examples but are missing or have stale
 * embeddings (generated by a different model than the currently configured one).
 * Only prompts with at least one approved example are relevant for few-shot retrieval.
 * Uses embedMany for efficient batching.
 */
export async function backfillEmbeddings(): Promise<BackfillResult> {
  const { model, config: embeddingCfg } = await resolveEmbeddingConfig();
  const currentModel = embeddingCfg.modelName;
  logger.info({ provider: embeddingCfg.provider, model: currentModel }, "resolving embedding model");

  const rows = await prisma.$queryRaw<{ id: string; prompt: string; description: string | null }[]>`
    SELECT DISTINCT p.id, p.prompt, p.description
    FROM workbench_example_prompts p
    JOIN workbench_examples e ON e.prompt_id = p.id
    WHERE e.approval_status IN ('auto_approved', 'human_approved')
      AND e.experiment_run_id IS NULL
      AND (p.embedding IS NULL
           OR p.embedding_model IS NULL
           OR p.embedding_model != ${currentModel})
    ORDER BY p.id
  `;

  if (rows.length === 0) {
    logger.info("nothing to backfill — all up to date");
    return { embedded: 0, skipped: 0 };
  }

  logger.info({ count: rows.length, model: currentModel }, "backfilling prompts");
  const BATCH_SIZE = 100;
  let embedded = 0;

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    const texts = batch.map((row) => row.description ? `${row.prompt}\n\n${row.description}` : row.prompt);

    logger.info({ batch: i / BATCH_SIZE + 1, size: batch.length }, "embedding batch");
    let embedResult;
    try {
      embedResult = await trackedEmbedMany({
        model,
        values: texts,
        providerOptions: { openai: { dimensions: EMBEDDING_DIMENSIONS } },
      }, {
        purpose: "embeddings",
        providerName: embeddingCfg.provider,
        modelId: embeddingCfg.id,
        modelName: embeddingCfg.modelName,
        modelConfig: {
          costPer1mInput: embeddingCfg.costPer1mInput,
          costPer1mOutput: embeddingCfg.costPer1mOutput,
        },
      });
    } catch (error) {
      const quotaError = asQuotaError(error, embeddingCfg.provider);
      if (quotaError) {
        logger.error({ err: quotaError, batch: i / BATCH_SIZE + 1 }, "provider quota exhausted — aborting backfill");
        throw quotaError;
      }
      logger.error({ err: error, batch: i / BATCH_SIZE + 1 }, "embedMany failed");
      throw error;
    }

    // Store each embedding + model name in a transaction
    await prisma.$transaction(async (tx) => {
      for (let j = 0; j < batch.length; j++) {
        const pgVector = `[${embedResult.embeddings[j].join(",")}]`;
        await tx.$executeRaw`
          UPDATE workbench_example_prompts
          SET embedding = ${pgVector}::vector, embedding_model = ${currentModel}
          WHERE id = ${batch[j].id}::uuid
        `;
      }
    });
    embedded += batch.length;
    logger.info({ embedded, total: rows.length }, "backfill progress");
  }

  return { embedded, skipped: 0 };
}

// ── Operation detection backfill ─────────────────────────────────────

/**
 * Backfill detected_operations — extracted to workbench-embeddings-backfill.service.ts.
 */
export { backfillDetectedOperations } from "./workbench-embeddings-backfill.service.js";

// ── Vector similarity search ────────────────────────────────────────

export interface FindSimilarResult {
  matches: FewShotMatch[];
  embeddingTokens: number;
}

/**
 * Find the most semantically similar approved examples across ALL categories.
 * Returns examples ordered by cosine similarity (highest first), plus embedding token usage.
 *
 * When `boostOperations` is provided, examples matching those operations get a
 * relevance boost (combined semantic + operation overlap score).
 */
export async function findSimilarExamples(
  promptText: string,
  limit = 6,
  boostOperations?: Set<string>,
  excludePromptIds?: string[],
): Promise<FindSimilarResult> {
  if (limit <= 0) return { matches: [], embeddingTokens: 0 };
  const { embedding: queryEmbedding, tokens: embeddingTokens } = await embedPromptTextWithUsage(promptText);
  const pgVector = `[${queryEmbedding.join(",")}]`;
  const exclusionIds = excludePromptIds && excludePromptIds.length > 0 ? excludePromptIds : null;

  if (boostOperations && boostOperations.size > 0) {
    const opsArray = [...boostOperations];
    // Fetch 3x candidates, then re-rank with operation overlap boost
    const candidateLimit = Math.min(limit * 3, 20);
    const candidates = exclusionIds
      ? await prisma.$queryRaw<{ prompt: string; code: string; similarity: number; detected_operations: string[] }[]>`
          SELECT p.prompt, e.code,
                  1 - (p.embedding <=> ${pgVector}::vector) AS similarity,
                  p.detected_operations
           FROM workbench_examples e
           JOIN workbench_example_prompts p ON p.id = e.prompt_id
           WHERE p.embedding IS NOT NULL
             AND e.approval_status IN ('auto_approved', 'human_approved')
             AND e.experiment_run_id IS NULL
             AND p.id != ALL(${exclusionIds}::uuid[])
           ORDER BY p.embedding <=> ${pgVector}::vector ASC
           LIMIT ${candidateLimit}
        `
      : await prisma.$queryRaw<{ prompt: string; code: string; similarity: number; detected_operations: string[] }[]>`
          SELECT p.prompt, e.code,
                  1 - (p.embedding <=> ${pgVector}::vector) AS similarity,
                  p.detected_operations
           FROM workbench_examples e
           JOIN workbench_example_prompts p ON p.id = e.prompt_id
           WHERE p.embedding IS NOT NULL
             AND e.approval_status IN ('auto_approved', 'human_approved')
             AND e.experiment_run_id IS NULL
           ORDER BY p.embedding <=> ${pgVector}::vector ASC
           LIMIT ${candidateLimit}
        `;

    // Re-rank: semantic similarity (0.7 weight) + operation overlap (0.3 weight)
    const ranked = candidates.map((c: { prompt: string; code: string; similarity: number; detected_operations: string[] }) => {
      const ops = c.detected_operations ?? [];
      const overlap = ops.filter((op: string) => opsArray.includes(op)).length;
      const overlapScore = opsArray.length > 0 ? overlap / opsArray.length : 0;
      const combined = c.similarity * 0.7 + overlapScore * 0.3;
      return { prompt: c.prompt, code: c.code, similarity: combined };
    });
    ranked.sort((a: { similarity: number }, b: { similarity: number }) => b.similarity - a.similarity);
    return { matches: ranked.slice(0, limit), embeddingTokens };
  }

  const rows = exclusionIds
    ? await prisma.$queryRaw<{ prompt: string; code: string; similarity: number }[]>`
        SELECT p.prompt, e.code,
                1 - (p.embedding <=> ${pgVector}::vector) AS similarity
         FROM workbench_examples e
         JOIN workbench_example_prompts p ON p.id = e.prompt_id
         WHERE p.embedding IS NOT NULL
           AND e.approval_status IN ('auto_approved', 'human_approved')
           AND e.experiment_run_id IS NULL
           AND p.id != ALL(${exclusionIds}::uuid[])
         ORDER BY p.embedding <=> ${pgVector}::vector ASC
         LIMIT ${limit}
      `
    : await prisma.$queryRaw<{ prompt: string; code: string; similarity: number }[]>`
        SELECT p.prompt, e.code,
                1 - (p.embedding <=> ${pgVector}::vector) AS similarity
         FROM workbench_examples e
         JOIN workbench_example_prompts p ON p.id = e.prompt_id
         WHERE p.embedding IS NOT NULL
           AND e.approval_status IN ('auto_approved', 'human_approved')
           AND e.experiment_run_id IS NULL
         ORDER BY p.embedding <=> ${pgVector}::vector ASC
         LIMIT ${limit}
      `;

  return { matches: rows, embeddingTokens };
}

// ── Similarity check for curation ────────────────────────────────────

export interface SimilarityMatch {
  prompt: string;
  similarity: number;
  exampleId: string;
  screenshotPath: string | null;
}

export interface SimilarityCheckResult {
  noveltyScore: number;
  maxSimilarity: number;
  matches: SimilarityMatch[];
}

/**
 * Check how similar a prompt is to existing approved workbench examples.
 * Returns top matches with example IDs and ISO screenshot paths for visual comparison.
 */
export async function checkSimilarity(
  promptText: string,
  limit = 5,
): Promise<SimilarityCheckResult> {
  const { embedding: queryEmbedding } = await embedPromptTextWithUsage(promptText);
  const pgVector = `[${queryEmbedding.join(",")}]`;

  const rows = await prisma.$queryRaw<{
    prompt: string;
    similarity: number;
    example_id: string;
    screenshot_iso: string | null;
  }[]>`
    SELECT p.prompt,
           1 - (p.embedding <=> ${pgVector}::vector) AS similarity,
           e.id AS example_id,
           e.screenshot_iso
     FROM workbench_examples e
     JOIN workbench_example_prompts p ON p.id = e.prompt_id
     WHERE p.embedding IS NOT NULL
       AND e.approval_status IN ('auto_approved', 'human_approved')
       AND e.experiment_run_id IS NULL
     ORDER BY p.embedding <=> ${pgVector}::vector ASC
     LIMIT ${limit}
  `;

  const maxSimilarity = rows.length > 0 ? Math.max(...rows.map((r) => r.similarity)) : 0;

  return {
    noveltyScore: Math.round((1 - maxSimilarity) * 100) / 100,
    maxSimilarity: Math.round(maxSimilarity * 100) / 100,
    matches: rows.map((r) => ({
      prompt: r.prompt,
      similarity: Math.round(r.similarity * 100) / 100,
      exampleId: r.example_id,
      screenshotPath: r.screenshot_iso,
    })),
  };
}

// ── Status ──────────────────────────────────────────────────────────

/**
 * Return counts of total, embedded, missing, and stale embeddings.
 * Only counts prompts that have at least one approved example (relevant for few-shot retrieval).
 * Stale = has an embedding but generated by a different model than currently configured.
 */
export async function getEmbeddingStatus(): Promise<EmbeddingStatus> {
  const { config: embeddingCfg } = await resolveEmbeddingConfig();
  const currentModel = embeddingCfg.modelName;
  const rows = await prisma.$queryRaw<{ total: string; embedded: string; current_model: string }[]>`
    SELECT
      COUNT(DISTINCT p.id)::text AS total,
      COUNT(DISTINCT CASE WHEN p.embedding IS NOT NULL THEN p.id END)::text AS embedded,
      COUNT(DISTINCT CASE WHEN p.embedding IS NOT NULL AND p.embedding_model = ${currentModel} THEN p.id END)::text AS current_model
    FROM workbench_example_prompts p
    JOIN workbench_examples e ON e.prompt_id = p.id
    WHERE e.approval_status IN ('auto_approved', 'human_approved')
      AND e.experiment_run_id IS NULL
  `;
  const row = rows[0];
  const total = Number(row.total);
  const embeddedCount = Number(row.embedded);
  const currentModelCount = Number(row.current_model);
  return {
    total,
    embedded: currentModelCount,
    missing: total - embeddedCount,
    stale: embeddedCount - currentModelCount,
    currentModel,
  };
}

// ── Spec embedding storage ───────────────────────────────────────────

/**
 * Store a construction spec and its embedding on a workbench prompt row.
 * Called after successful generation to build the spec embedding pool.
 * Respects the global.remix_spec_embedding_enabled setting.
 */
export async function storeSpecAndEmbedding(
  promptId: string,
  constructionSpec: string,
): Promise<void> {
  const enabled = await isSpecEmbeddingEnabled();
  if (!enabled) {
    logger.debug("spec embedding disabled, storing text only");
    await prisma.workbenchExamplePrompt.update({
      where: { id: promptId },
      data: { constructionSpec },
    });
    return;
  }

  const { embedding } = await embedPromptTextWithUsage(constructionSpec);
  const pgVector = `[${embedding.join(",")}]`;

  const cfg = await getModelForPurpose("embedding");

  await prisma.$executeRaw`
    UPDATE workbench_example_prompts
    SET construction_spec = ${constructionSpec},
        spec_embedding = ${pgVector}::vector,
        spec_embedding_model = ${cfg.modelName}
    WHERE id = ${promptId}::uuid
  `;

  logger.debug({ promptId }, "stored spec and embedding");
}
