/**
 * Workbench Embeddings Service
 *
 * Generates and stores vector embeddings for workbench example prompts.
 * Used for semantic similarity search when selecting few-shot examples
 * for the code generation pipeline.
 */

import { embed, embedMany } from "ai";
import { pool } from "../db/connection.js";
import { createLogger } from "../utils/logger.js";
import {
  getModelForPurpose,
  createEmbeddingModel,
  type LlmModelConfig,
} from "./llm-config.service.js";

const logger = createLogger("embeddings");

// ── Types ────────────────────────────────────────────────────────────

export interface FewShotMatch {
  prompt: string;
  code: string;
  similarity: number;
}

export interface EmbeddingStatus {
  total: number;
  embedded: number;
  missing: number;
  stale: number;
  currentModel: string;
}

export interface BackfillResult {
  embedded: number;
  skipped: number;
}

// ── Provider setup ──────────────────────────────────────────────────

// Target dimension for pgvector index compatibility (max 2000 for HNSW/IVFFlat)
// text-embedding-3-large with dimensions=1536 produces better quality than
// text-embedding-3-small at the same dimension via Matryoshka Representation Learning.
const EMBEDDING_DIMENSIONS = 1536;

/**
 * Resolve the embedding model from the DB-driven llm_purpose_map.
 * Returns the Vercel AI SDK embedding model instance and config.
 */
async function resolveEmbeddingConfig(): Promise<{ model: ReturnType<typeof createEmbeddingModel>; config: LlmModelConfig }> {
  const cfg = await getModelForPurpose("embedding");
  const model = createEmbeddingModel(cfg);
  return { model, config: cfg };
}

// ── Core embedding functions ────────────────────────────────────────

/**
 * Embed a single text string into a vector.
 */
export async function embedPromptText(text: string): Promise<number[]> {
  const { model } = await resolveEmbeddingConfig();
  const result = await embed({
    model,
    value: text,
    providerOptions: { openai: { dimensions: EMBEDDING_DIMENSIONS } },
  });
  return result.embedding;
}

/**
 * Embed a prompt and store the vector + model name in the database.
 */
export async function embedAndStorePrompt(promptId: string, promptText: string): Promise<void> {
  const { config: embeddingCfg } = await resolveEmbeddingConfig();
  const embedding = await embedPromptText(promptText);
  const pgVector = `[${embedding.join(",")}]`;
  await pool.query(
    `UPDATE workbench_example_prompts SET embedding = $2::vector, embedding_model = $3 WHERE id = $1`,
    [promptId, pgVector, embeddingCfg.modelName],
  );
}

// ── Backfill ────────────────────────────────────────────────────────

/**
 * Batch-embed prompts that have approved examples but are missing or have stale
 * embeddings (generated by a different model than the currently configured one).
 * Only prompts with at least one approved example are relevant for few-shot retrieval.
 * Uses embedMany for efficient batching.
 */
export async function backfillEmbeddings(): Promise<BackfillResult> {
  const { model, config: embeddingCfg } = await resolveEmbeddingConfig();
  const currentModel = embeddingCfg.modelName;
  logger.info({ provider: embeddingCfg.provider, model: currentModel }, "resolving embedding model");

  const result = await pool.query<{ id: string; prompt: string }>(
    `SELECT DISTINCT p.id, p.prompt
     FROM workbench_example_prompts p
     JOIN workbench_examples e ON e.prompt_id = p.id
     WHERE e.approval_status IN ('auto_approved', 'human_approved')
       AND (p.embedding IS NULL
            OR p.embedding_model IS NULL
            OR p.embedding_model != $1)
     ORDER BY p.id`,
    [currentModel],
  );

  if (result.rows.length === 0) {
    logger.info("nothing to backfill — all up to date");
    return { embedded: 0, skipped: 0 };
  }

  logger.info({ count: result.rows.length, model: currentModel }, "backfilling prompts");
  const BATCH_SIZE = 100;
  let embedded = 0;

  for (let i = 0; i < result.rows.length; i += BATCH_SIZE) {
    const batch = result.rows.slice(i, i + BATCH_SIZE);
    const texts = batch.map((row) => row.prompt);

    logger.info({ batch: i / BATCH_SIZE + 1, size: batch.length }, "embedding batch");
    let embedResult;
    try {
      embedResult = await embedMany({
        model,
        values: texts,
        providerOptions: { openai: { dimensions: EMBEDDING_DIMENSIONS } },
      });
    } catch (error) {
      logger.error({ err: error, batch: i / BATCH_SIZE + 1 }, "embedMany failed");
      throw error;
    }

    // Store each embedding + model name in a transaction
    const client = await pool.connect();
    try {
      await client.query("BEGIN");
      for (let j = 0; j < batch.length; j++) {
        const pgVector = `[${embedResult.embeddings[j].join(",")}]`;
        await client.query(
          `UPDATE workbench_example_prompts
           SET embedding = $2::vector, embedding_model = $3
           WHERE id = $1`,
          [batch[j].id, pgVector, currentModel],
        );
      }
      await client.query("COMMIT");
      embedded += batch.length;
      logger.info({ embedded, total: result.rows.length }, "backfill progress");
    } catch (error) {
      await client.query("ROLLBACK");
      logger.error({ err: error, batch: i / BATCH_SIZE + 1 }, "DB store failed");
      throw error;
    } finally {
      client.release();
    }
  }

  return { embedded, skipped: 0 };
}

// ── Vector similarity search ────────────────────────────────────────

/**
 * Find the most semantically similar approved examples across ALL categories.
 * Returns examples ordered by cosine similarity (highest first).
 */
export async function findSimilarExamples(
  promptText: string,
  limit = 6,
): Promise<FewShotMatch[]> {
  const queryEmbedding = await embedPromptText(promptText);
  const pgVector = `[${queryEmbedding.join(",")}]`;

  const result = await pool.query<{ prompt: string; code: string; similarity: number }>(
    `SELECT p.prompt, e.code,
            1 - (p.embedding <=> $1::vector) AS similarity
     FROM workbench_examples e
     JOIN workbench_example_prompts p ON p.id = e.prompt_id
     WHERE p.embedding IS NOT NULL
       AND e.approval_status IN ('auto_approved', 'human_approved')
     ORDER BY p.embedding <=> $1::vector ASC
     LIMIT $2`,
    [pgVector, limit],
  );

  return result.rows;
}

// ── Status ──────────────────────────────────────────────────────────

/**
 * Return counts of total, embedded, missing, and stale embeddings.
 * Only counts prompts that have at least one approved example (relevant for few-shot retrieval).
 * Stale = has an embedding but generated by a different model than currently configured.
 */
export async function getEmbeddingStatus(): Promise<EmbeddingStatus> {
  const { config: embeddingCfg } = await resolveEmbeddingConfig();
  const currentModel = embeddingCfg.modelName;
  const result = await pool.query<{ total: string; embedded: string; current_model: string }>(`
    SELECT
      COUNT(DISTINCT p.id)::text AS total,
      COUNT(DISTINCT CASE WHEN p.embedding IS NOT NULL THEN p.id END)::text AS embedded,
      COUNT(DISTINCT CASE WHEN p.embedding IS NOT NULL AND p.embedding_model = $1 THEN p.id END)::text AS current_model
    FROM workbench_example_prompts p
    JOIN workbench_examples e ON e.prompt_id = p.id
    WHERE e.approval_status IN ('auto_approved', 'human_approved')
  `, [currentModel]);
  const row = result.rows[0];
  const total = Number(row.total);
  const embeddedCount = Number(row.embedded);
  const currentModelCount = Number(row.current_model);
  return {
    total,
    embedded: currentModelCount,
    missing: total - embeddedCount,
    stale: embeddedCount - currentModelCount,
    currentModel,
  };
}
