/**
 * Workbench Embeddings Service
 *
 * Generates and stores vector embeddings for workbench example prompts.
 * Used for semantic similarity search when selecting few-shot examples
 * for the code generation pipeline.
 */

import { embed, embedMany } from "ai";
import { asQuotaError } from "../utils/llm-errors.js";
import { prisma } from "../db/prisma.js";
import { createLogger } from "../utils/logger.js";
import {
  getModelForPurpose,
  createEmbeddingModel,
  type LlmModelConfig,
} from "./llm-config.service.js";

const logger = createLogger("embeddings");

// ── Types ────────────────────────────────────────────────────────────

export interface FewShotMatch {
  prompt: string;
  code: string;
  similarity: number;
}

export interface EmbeddingStatus {
  total: number;
  embedded: number;
  missing: number;
  stale: number;
  currentModel: string;
}

export interface BackfillResult {
  embedded: number;
  skipped: number;
}

// ── Provider setup ──────────────────────────────────────────────────

// Target dimension for pgvector index compatibility (max 2000 for HNSW/IVFFlat)
// text-embedding-3-large with dimensions=1536 produces better quality than
// text-embedding-3-small at the same dimension via Matryoshka Representation Learning.
const EMBEDDING_DIMENSIONS = 1536;

/**
 * Resolve the embedding model from the DB-driven llm_purpose_map.
 * Returns the Vercel AI SDK embedding model instance and config.
 */
async function resolveEmbeddingConfig(): Promise<{ model: ReturnType<typeof createEmbeddingModel>; config: LlmModelConfig }> {
  const cfg = await getModelForPurpose("embedding");
  const model = createEmbeddingModel(cfg);
  return { model, config: cfg };
}

// ── Core embedding functions ────────────────────────────────────────

/**
 * Embed a single text string into a vector.
 */
export async function embedPromptText(text: string): Promise<number[]> {
  const { embedding } = await embedPromptTextWithUsage(text);
  return embedding;
}

/**
 * Embed a single text string into a vector, also returning token usage.
 */
export async function embedPromptTextWithUsage(text: string): Promise<{ embedding: number[]; tokens: number }> {
  const { model, config: cfg } = await resolveEmbeddingConfig();
  try {
    const result = await embed({
      model,
      value: text,
      providerOptions: { openai: { dimensions: EMBEDDING_DIMENSIONS } },
    });
    return { embedding: result.embedding, tokens: result.usage?.tokens ?? 0 };
  } catch (error) {
    const quotaError = asQuotaError(error, cfg.provider);
    if (quotaError) throw quotaError;
    throw error;
  }
}

/**
 * Embed a prompt and store the vector + model name in the database.
 */
export async function embedAndStorePrompt(promptId: string, promptText: string): Promise<void> {
  const { config: embeddingCfg } = await resolveEmbeddingConfig();
  const embedding = await embedPromptText(promptText);
  const pgVector = `[${embedding.join(",")}]`;
  await prisma.$executeRaw`
    UPDATE workbench_example_prompts SET embedding = ${pgVector}::vector, embedding_model = ${embeddingCfg.modelName} WHERE id = ${promptId}::uuid
  `;
}

// ── Backfill ────────────────────────────────────────────────────────

/**
 * Batch-embed prompts that have approved examples but are missing or have stale
 * embeddings (generated by a different model than the currently configured one).
 * Only prompts with at least one approved example are relevant for few-shot retrieval.
 * Uses embedMany for efficient batching.
 */
export async function backfillEmbeddings(): Promise<BackfillResult> {
  const { model, config: embeddingCfg } = await resolveEmbeddingConfig();
  const currentModel = embeddingCfg.modelName;
  logger.info({ provider: embeddingCfg.provider, model: currentModel }, "resolving embedding model");

  const rows = await prisma.$queryRaw<{ id: string; prompt: string }[]>`
    SELECT DISTINCT p.id, p.prompt
    FROM workbench_example_prompts p
    JOIN workbench_examples e ON e.prompt_id = p.id
    WHERE e.approval_status IN ('auto_approved', 'human_approved')
      AND (p.embedding IS NULL
           OR p.embedding_model IS NULL
           OR p.embedding_model != ${currentModel})
    ORDER BY p.id
  `;

  if (rows.length === 0) {
    logger.info("nothing to backfill — all up to date");
    return { embedded: 0, skipped: 0 };
  }

  logger.info({ count: rows.length, model: currentModel }, "backfilling prompts");
  const BATCH_SIZE = 100;
  let embedded = 0;

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);
    const texts = batch.map((row) => row.prompt);

    logger.info({ batch: i / BATCH_SIZE + 1, size: batch.length }, "embedding batch");
    let embedResult;
    try {
      embedResult = await embedMany({
        model,
        values: texts,
        providerOptions: { openai: { dimensions: EMBEDDING_DIMENSIONS } },
      });
    } catch (error) {
      const quotaError = asQuotaError(error, embeddingCfg.provider);
      if (quotaError) {
        logger.error({ err: quotaError, batch: i / BATCH_SIZE + 1 }, "provider quota exhausted — aborting backfill");
        throw quotaError;
      }
      logger.error({ err: error, batch: i / BATCH_SIZE + 1 }, "embedMany failed");
      throw error;
    }

    // Store each embedding + model name in a transaction
    await prisma.$transaction(async (tx) => {
      for (let j = 0; j < batch.length; j++) {
        const pgVector = `[${embedResult.embeddings[j].join(",")}]`;
        await tx.$executeRaw`
          UPDATE workbench_example_prompts
          SET embedding = ${pgVector}::vector, embedding_model = ${currentModel}
          WHERE id = ${batch[j].id}::uuid
        `;
      }
    });
    embedded += batch.length;
    logger.info({ embedded, total: rows.length }, "backfill progress");
  }

  return { embedded, skipped: 0 };
}

// ── Vector similarity search ────────────────────────────────────────

export interface FindSimilarResult {
  matches: FewShotMatch[];
  embeddingTokens: number;
}

/**
 * Find the most semantically similar approved examples across ALL categories.
 * Returns examples ordered by cosine similarity (highest first), plus embedding token usage.
 */
export async function findSimilarExamples(
  promptText: string,
  limit = 6,
): Promise<FindSimilarResult> {
  const { embedding: queryEmbedding, tokens: embeddingTokens } = await embedPromptTextWithUsage(promptText);
  const pgVector = `[${queryEmbedding.join(",")}]`;

  const rows = await prisma.$queryRaw<{ prompt: string; code: string; similarity: number }[]>`
    SELECT p.prompt, e.code,
            1 - (p.embedding <=> ${pgVector}::vector) AS similarity
     FROM workbench_examples e
     JOIN workbench_example_prompts p ON p.id = e.prompt_id
     WHERE p.embedding IS NOT NULL
       AND e.approval_status IN ('auto_approved', 'human_approved')
     ORDER BY p.embedding <=> ${pgVector}::vector ASC
     LIMIT ${limit}
  `;

  return { matches: rows, embeddingTokens };
}

// ── Status ──────────────────────────────────────────────────────────

/**
 * Return counts of total, embedded, missing, and stale embeddings.
 * Only counts prompts that have at least one approved example (relevant for few-shot retrieval).
 * Stale = has an embedding but generated by a different model than currently configured.
 */
export async function getEmbeddingStatus(): Promise<EmbeddingStatus> {
  const { config: embeddingCfg } = await resolveEmbeddingConfig();
  const currentModel = embeddingCfg.modelName;
  const rows = await prisma.$queryRaw<{ total: string; embedded: string; current_model: string }[]>`
    SELECT
      COUNT(DISTINCT p.id)::text AS total,
      COUNT(DISTINCT CASE WHEN p.embedding IS NOT NULL THEN p.id END)::text AS embedded,
      COUNT(DISTINCT CASE WHEN p.embedding IS NOT NULL AND p.embedding_model = ${currentModel} THEN p.id END)::text AS current_model
    FROM workbench_example_prompts p
    JOIN workbench_examples e ON e.prompt_id = p.id
    WHERE e.approval_status IN ('auto_approved', 'human_approved')
  `;
  const row = rows[0];
  const total = Number(row.total);
  const embeddedCount = Number(row.embedded);
  const currentModelCount = Number(row.current_model);
  return {
    total,
    embedded: currentModelCount,
    missing: total - embeddedCount,
    stale: embeddedCount - currentModelCount,
    currentModel,
  };
}
